m = open("/run/secrets/mistral")
mistral_api_key = m.read()
m.close()
p = open("/run/secrets/phoenix")
phoenix_api_key = p.read()
p.close()
l = open("/run/secrets/llamacloud")
llamacloud_api_key = l.read()
l.close()